### ISSUE TITLE
more keys than enter should work on the menu

### ISSUE THREAD

**Issue by sergiocornaga** [Raicuparta/curvatron#92]
I'd like to see spacebar work, for instance. It took me a while to notice keys worked at all since enter's not the first thing I typically try.

**Comment by Raicuparta** [comment]
do the arrow keys not work for you?

**Comment by sergiocornaga** [comment]
Apologies, I meant solely for confirming choices.

**Comment by Raicuparta** [comment]
OK, I've thought about this before myself. So the keys that are configured for player movement should also act as a the "select" button on the menus, correct?

**Comment by sergiocornaga** [comment]
That would make sense to me.
